//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagementAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionManagement
    {
        public System.Guid SessionGuiId { get; set; }
        public string UserName { get; set; }
        public string IpAddress { get; set; }
        public string MachineName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime EndDate { get; set; }
    }
}
